stages:
  - test

pylint:
  image: python:3.6-alpine
  stage: test
  tags:
    - docker
  script:
    - apk add -U git
    - pip install pylint
    - pylint --rcfile=.pylintrc $(git ls-tree --name-only --full-tree -r HEAD | grep '\.py' | sort | tr '\n' ' ') || RETCODE=1

unittest:
  image: python:3.6-alpine
  stage: test
  cache:
    paths:
      - build/
  script:
    - apk add -U bash gcc gnupg linux-headers musl-dev npm py2-virtualenv > /dev/null 2>&1
    - mkdir /etc/upgrade
    - touch /etc/builddate
    - ./tellstick.sh setup > /dev/null 2>&1
    - ./tellstick.sh install events > /dev/null 2>&1
    - ./tellstick.sh install scheduler > /dev/null 2>&1
    - ./tellstick.sh install upgrade > /dev/null 2>&1
    - ./tellstick.sh test
